### PR TITLE
Source required objects

### PR DESCRIPTION
**Pull request by henrykironde**

### CODE REVIEW

**Comment by ethanwhite** [comment]
This looks good to me, but let's @Juniper Simonis have a look since it's their changes that are getting updated.

The big question is how to deal with the 1000's of extra files that got added in bd8b003b3428d25e67417dfb0302a1934db26fe4. If we just deleted them in a new commit we're going to end up carrying around about a gig of files in the history forever, so I'd like to get rid of them entirely. It's a littletricky because there are changes tied up in that commit that we want to keep (though I think it's only one meaningful line).

Proposal (which I think may work but we'd have to test):

1. Interactive rebase to drop bd8b003b3428d25e67417dfb0302a1934db26fe4
2. Add a new commit with the one line change that is the core of that commit
3. git filter-repo to scrub those directories from the tree (something like `git filter-repo --path forecasts/ --path resources/ --invert-paths`)
4. Force push this into main (after turning off the branch protection temporarily)
5. Then rebase your current branch or cherry-pick https://github.com/weecology/portal-forecast-web/pull/41/commits/2d4d202d522411edea25df57c2f395410deb2bad into a new one to integrate your fixes.

Thoughts?

**Review by juniperlsimonis — APPROVED** [review]

**Comment by henrykironde** [comment]
Oh no

**Comment by juniperlsimonis** [comment]
> Oh no

??

**Comment by ethanwhite** [comment]
Looks like @henrykironde accidentally merged without the history clean up described above, but I think we can just do steps (1)-(4) now and everything should work the same.

**Pull request merged**
