### PR TITLE
Refactor for reactive inputs

### PR DESCRIPTION
**Pull request by juniperlsimonis**
full website with forecast and evaluations tabs as well as static pages
now inputs are reactive and the result is allowing the full set of models in the dropdown but only when they're available
right now, the reactions are based on some simple rules and conditionals. ideally we'll move to pulling the availabilities from the casts metadata file, but that's going to take additional work on the portalcasting side

### CODE REVIEW

**Comment by juniperlsimonis** [comment]
@henrykironde let me know if you want to walk through this together on a call or anything
thanks!

**Comment by henrykironde** [comment]
I have gone through the code but let us go through it together when you get time.

**Comment by juniperlsimonis** [comment]
> I am getting an error `Warning: Error in rodent_species: could not find function "rodent_species"`

@henrykironde thats a portalcasting function, so presumably it means there needs to be a `library(portalcasting)` inserted somewhere. can you try putting one in the server_functions.R script (at the top, not in any function) and see if that works?

**Comment by henrykironde** [comment]
We need that line` library(portalcasting)` in `ui.R`

**Review by henrykironde — APPROVED** [review]

**Comment by henrykironde** [comment]
@juniperlsimonis thank you for the updates

**Pull request merged**
