### PR TITLE
tidying code

### PR DESCRIPTION
**Pull request by juniperlsimonis**
* added a `main` argument to `server()` to allow redirection
* removed intermediate objects in `renderPlot()` functions to patch inputs directly to arguments

### CODE REVIEW

**Comment by henrykironde** [comment]
@juniperlsimonis this looks good to me. Just a few questions. Does this mean that we are setting the data directory to `~/portalcasting`?

**Comment by henrykironde** [comment]
Do we need to change this line https://github.com/weecology/portal-forecast-web/blob/main/update_repo.sh#L18 ?

**Comment by juniperlsimonis** [comment]
ah, no, thanks for catching that, it should be ".", which is the default for all the functions, i had it set to "~/portalcasting" for local work. just updated

**Review by henrykironde — COMMENTED** [review]
I will run some local tests and get this in

**Comment by henrykironde** [comment]
At the moment I can't download and test the PR. I think it is the network problem where I am. I will try later.
```R
Downloading version `3.166.0` of the data...
Error in download.file(zipball_url, temp, quiet = !verbose, mode = "wb") : 
  download from 'https://api.github.com/repos/weecology/PortalData/zipball/3.166.0' failed
Calls: setup_production ... fill_resources -> download_observations -> download.file
In addition: Warning message:
In download.file(zipball_url, temp, quiet = !verbose, mode = "wb") :
  URL 'https://codeload.github.com/weecology/PortalData/legacy.zip/refs/tags/3.166.0': Timeout of 60 seconds was reached
Execution halted
```

**Review by henrykironde — APPROVED** [review]

**Pull request merged**
